services:
  backend:
    build:
      context: ./backend
    ports:
      - "10081:10081"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/indexlive
      - PORT=10081
      - PROJECT_ID=1957
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "10084:10084"
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=http://localhost:10081

  mongo:
    image: mongo:4.4
    ports:
      - "10085:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: